config/routes.rb
Web::Application.routes.draw do
  resources :maps

  root :to => "maps#index"

end

app/models/map.rb
class Map < ActiveRecord::Base
  validates_presence_of :name, :description
  
  has_many :points, :dependent => :delete_all
end

app/models/point.rb
class Point < ActiveRecord::Base
  validates_presence_of :lat, :lng, :marker_identifier
  
  scope :for_editing, select("description, lat, lng")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /maps
  # GET /maps.xml
  def index
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.xml
  def show
    @map = Map.find_by_id(params[:id])
    @saved_locations = @map.points.for_editing.to_json

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.xml
  def new
    @map = Map.new

    puts @saved_locations
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find_by_id(params[:id])
    @saved_locations = @map.points.for_editing.to_json
  end

  # POST /maps
  # POST /maps.xml
  def create
    @map = Map.new(params[:map])
    @map.name = "Map Created #{Time.now.strftime('at %I:%M%p')}" if @map.name.blank?
    @map.description = "No Description Provided" if @map.description.blank?
    if points = params['markers']
      points.each do |marker_identifier, point|
        @map.points.build(:lat => point['lat'].to_f,:lng => point['lng'].to_f,:description =>point['description'], :marker_identifier => marker_identifier)
      end
    end
    respond_to do |format|
      if @map.save
        format.html { redirect_to(@map, :notice => 'Map was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.xml
  def update
    @map = Map.find_by_id(params[:id])
    new_points = []
    if points = params['markers']
      points.each do |marker_identifier,point|
        new_points << @map.points.build(:marker_identifier => marker_identifier, :lat => point['lat'], :lng => point['lng'],:description =>point['description'])
      end
    end
    @map.points = new_points    
    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to(@map, :notice => 'Map was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.xml
  def destroy
    @map = Map.find_by_id(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to(maps_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, 'jquery_color' %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="content"><%= yield %></div>
	
	<span class="tiny_goodbye_box italics">
		See ya! Thanks for stopping by. Bored? That sucks. Learn to program.
	</span>
</body>
</html>

app/views/maps/_form.html.erb
<%= javascript_include_tag 'map' %>
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Give me a name' %>
    <br />
    <%= f.text_field :name %>
  </div>
  <div id="points_scroller">
      <ul id="points">
      </ul>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %> or <%= link_to 'Cancel', maps_path %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"> </script>
<script type="text/javascript" >
  var data_set = <%= raw @saved_locations %>;
</script>
<div class="container">
  <div id="new_map_details" class="left">
	<%= javascript_include_tag 'map' %>
	<%= form_for(@map) do |f| %>
	  <% if @map.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

	      <ul>
	      <% @map.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="field">
	    <%= f.label :name %>
	    <br />
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :description %>
	    <br /><%= f.text_field :description %>
	  </div>
	  <div id="points_scroller">
	      <ul id="points">
	      </ul>
	  </div>
	  <div class="actions">
	    <%= f.submit 'Save' %> or <%= link_to 'Cancel', maps_path %>
	  </div>
	<% end %>
  </div>
  <div class="map_points right">
    Go to a location: <input id="address" type="textbox" value="Sunnyvale, CA"> <input type="button" value="Geocode" onclick="codeAddress()">
    <div id="map_canvas"></div>
  </div>
</div>
<div style="clear:both"></div>

app/views/maps/index.html.erb
<div id="messages">
	<span class="welcome_box background_grey">
		social mapper is totally uhhhhhh google map sub-feature no one uses.
	</span>
	<br />
	<span class="welcome_box background_orange italics">
		i've got no more secrets. get on with it.
	</span>
	<br />
	<span class="welcome_box background_orange italics">
		yeaaaahh <%= link_to 'create a new map', new_map_path %>
	</span>
</div>

<h1>these are my maps. ugh. they're heavy.</h1>

<% @maps.each do |map| %>
<div><span class="themed_entry"><%= link_to map.name, map %></span></div>
<% end %>
<br />

app/views/maps/new.html.erb
<div id="messages">
	<span class="welcome_box background_grey">
		okay step 1: double click on the map to add a point
	</span>
	<br />
	<span class="welcome_box background_orange italics">
		yup, step 2: you're pretty much done
	</span>
	<br />
	<span class="welcome_box background_orange italics">
		baaaaaaaaam: describe the points & save
	</span>
</div>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"> </script>
<script type="text/javascript" >
  var data_set = null;
</script>
<div class="container">
  <div id="new_map_details" class="left">
	<%= javascript_include_tag 'map' %>
	<%= form_for(@map) do |f| %>
	  <% if @map.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

	      <ul>
	      <% @map.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="field">
	    <%= f.label :name, 'what is this map about?' %>
	    <br />
	    <%= f.text_field :name %>
	  </div>
	  <div id="points_scroller">
	      <ul id="points">
	      </ul>
	  </div>
	  <div class="actions">
	    <%= f.submit 'Save' %> or <%= link_to 'Cancel', maps_path %>
	  </div>
	<% end %>
  </div>
  <div class="map_points right">
    <label for='address'>Go to a location:</label> <input id="address" type="textbox" value="Sunnyvale, CA"> <input type="button" value="Whisk me away" onclick="codeAddress()">
    <div id="map_canvas"></div>
  </div>
</div>
<div style="clear:both"></div>

app/views/maps/show.html.erb
<div id="messages">
	<span class="welcome_box background_grey">
		this is a super special map...
	</span>
	<br />
	<span class="welcome_box background_orange italics">
		titled, <%= @map.name %>
	</span>
	<br />
	<span class="welcome_box background_orange italics">
		and described, <%= @map.description %>
	</span>
	<br />
	<span class="welcome_box background_grey">
		oh, and when you're done you can <%= link_to 'go back to all the maps', maps_path %>
	</span>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"> </script>
<script type="text/javascript" >
  var data_set = <%= raw @saved_locations %>;
	var view_only = true;
</script>
<div class="container">
  <div id="new_map_details" class="left">
	<%= javascript_include_tag 'map' %>
	<span class='give_me_spce'>points on the map...</span>
	  <div id="points_scroller">
	      <ul id="points">
	      </ul>
	  </div>
  </div>
  <div class="map_points right">
    <div id="map_canvas"></div>
  </div>
</div>
<div style="clear:both"></div>